/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

(* top =  1  *)
(* src = "controlador.v:1.1-119.10" *)
module controlador(CLK, RESET, TARJETA_RECIBIDA, TIPO_TRANS, DIGITO_STB, MONTO_STB, DIGITO, PIN, MONTO, BALANCE_ACTUALIZADO, ENTREGAR_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO_CTRL, FONDOS_INSUFICIENTES);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  (* src = "controlador.v:6.70-6.81" *)
  output ADVERTENCIA;
  wire ADVERTENCIA;
  (* src = "controlador.v:21.12-21.19" *)
  wire [31:0] BALANCE;
  (* src = "controlador.v:6.16-6.35" *)
  output BALANCE_ACTUALIZADO;
  wire BALANCE_ACTUALIZADO;
  (* src = "controlador.v:6.83-6.95" *)
  output BLOQUEO_CTRL;
  wire BLOQUEO_CTRL;
  (* src = "controlador.v:2.11-2.14" *)
  input CLK;
  wire CLK;
  (* src = "controlador.v:3.17-3.23" *)
  input [3:0] DIGITO;
  wire [3:0] DIGITO;
  (* src = "controlador.v:2.53-2.63" *)
  input DIGITO_STB;
  wire DIGITO_STB;
  (* src = "controlador.v:6.37-6.52" *)
  output ENTREGAR_DINERO;
  wire ENTREGAR_DINERO;
  (* src = "controlador.v:6.97-6.117" *)
  output FONDOS_INSUFICIENTES;
  wire FONDOS_INSUFICIENTES;
  (* src = "controlador.v:5.18-5.23" *)
  input [31:0] MONTO;
  wire [31:0] MONTO;
  (* src = "controlador.v:2.65-2.74" *)
  input MONTO_STB;
  wire MONTO_STB;
  (* src = "controlador.v:4.18-4.21" *)
  input [15:0] PIN;
  wire [15:0] PIN;
  (* src = "controlador.v:6.54-6.68" *)
  output PIN_INCORRECTO;
  wire PIN_INCORRECTO;
  (* src = "controlador.v:2.16-2.21" *)
  input RESET;
  wire RESET;
  (* src = "controlador.v:2.23-2.39" *)
  input TARJETA_RECIBIDA;
  wire TARJETA_RECIBIDA;
  (* src = "controlador.v:2.41-2.51" *)
  input TIPO_TRANS;
  wire TIPO_TRANS;
  (* src = "controlador.v:19.11-19.18" *)
  wire [3:0] counter;
  (* src = "controlador.v:17.11-17.17" *)
  wire [6:0] estado;
  (* src = "controlador.v:23.12-23.25" *)
  wire [15:0] pin_ingresado;
  (* src = "controlador.v:17.19-17.33" *)
  (* unused_bits = "0 1 2 3 4 5 6" *)
  wire [6:0] proximo_estado;
  NOT _081_ (
    .A(estado[6]),
    .Y(_037_)
  );
  NOT _082_ (
    .A(estado[5]),
    .Y(_038_)
  );
  NOT _083_ (
    .A(estado[4]),
    .Y(_039_)
  );
  NOT _084_ (
    .A(estado[3]),
    .Y(_040_)
  );
  NOT _085_ (
    .A(estado[0]),
    .Y(_041_)
  );
  NOT _086_ (
    .A(MONTO[15]),
    .Y(_042_)
  );
  NOT _087_ (
    .A(TARJETA_RECIBIDA),
    .Y(_043_)
  );
  NOT _088_ (
    .A(TIPO_TRANS),
    .Y(_044_)
  );
  NOT _089_ (
    .A(MONTO[8]),
    .Y(_045_)
  );
  NOR _090_ (
    .A(estado[5]),
    .B(estado[4]),
    .Y(_046_)
  );
  NAND _091_ (
    .A(_037_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _092_ (
    .A(estado[4]),
    .B(estado[3]),
    .Y(_048_)
  );
  NOR _093_ (
    .A(estado[1]),
    .B(_041_),
    .Y(_049_)
  );
  NAND _094_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _095_ (
    .A(_047_),
    .B(_050_),
    .Y(_051_)
  );
  NOT _096_ (
    .A(_051_),
    .Y(_052_)
  );
  NOR _097_ (
    .A(_043_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _098_ (
    .A(TARJETA_RECIBIDA),
    .B(_051_),
    .Y(_054_)
  );
  NOR _099_ (
    .A(estado[1]),
    .B(estado[0]),
    .Y(_055_)
  );
  NAND _100_ (
    .A(_048_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _101_ (
    .A(_037_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _102_ (
    .A(_046_),
    .B(_057_),
    .Y(_058_)
  );
  NOT _103_ (
    .A(_058_),
    .Y(_059_)
  );
  NOR _104_ (
    .A(_038_),
    .B(_056_),
    .Y(_060_)
  );
  NAND _105_ (
    .A(_037_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _106_ (
    .A(_058_),
    .B(_061_),
    .Y(_062_)
  );
  NOT _107_ (
    .A(_062_),
    .Y(_063_)
  );
  NOR _108_ (
    .A(_040_),
    .B(_047_),
    .Y(_064_)
  );
  NAND _109_ (
    .A(_055_),
    .B(_064_),
    .Y(_065_)
  );
  NOT _110_ (
    .A(_065_),
    .Y(_066_)
  );
  NOR _111_ (
    .A(_062_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _112_ (
    .A(_063_),
    .B(_065_),
    .Y(_068_)
  );
  NOR _113_ (
    .A(_053_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _114_ (
    .A(_054_),
    .B(_067_),
    .Y(_070_)
  );
  NAND _115_ (
    .A(estado[0]),
    .B(_069_),
    .Y(_071_)
  );
  NOR _116_ (
    .A(RESET),
    .B(_062_),
    .Y(_072_)
  );
  NAND _117_ (
    .A(_071_),
    .B(_072_),
    .Y(_000_)
  );
  NOR _118_ (
    .A(estado[1]),
    .B(_053_),
    .Y(_073_)
  );
  NOR _119_ (
    .A(RESET),
    .B(_073_),
    .Y(_001_)
  );
  NAND _120_ (
    .A(estado[3]),
    .B(_069_),
    .Y(_074_)
  );
  NOR _121_ (
    .A(RESET),
    .B(_074_),
    .Y(_002_)
  );
  NOR _122_ (
    .A(_039_),
    .B(RESET),
    .Y(_003_)
  );
  NOR _123_ (
    .A(_038_),
    .B(_070_),
    .Y(_075_)
  );
  NOR _124_ (
    .A(TIPO_TRANS),
    .B(_065_),
    .Y(_076_)
  );
  NOR _125_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _126_ (
    .A(RESET),
    .B(_077_),
    .Y(_004_)
  );
  NOR _127_ (
    .A(_037_),
    .B(_070_),
    .Y(_078_)
  );
  NOR _128_ (
    .A(_044_),
    .B(_065_),
    .Y(_079_)
  );
  NOR _129_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _130_ (
    .A(RESET),
    .B(_080_),
    .Y(_005_)
  );
  NOR _131_ (
    .A(MONTO[6]),
    .B(MONTO[3]),
    .Y(_006_)
  );
  NOR _132_ (
    .A(MONTO[4]),
    .B(MONTO[5]),
    .Y(_007_)
  );
  NAND _133_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  NAND _134_ (
    .A(MONTO[7]),
    .B(MONTO[9]),
    .Y(_009_)
  );
  NOR _135_ (
    .A(_045_),
    .B(_009_),
    .Y(_010_)
  );
  NAND _136_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _137_ (
    .A(MONTO[10]),
    .B(MONTO[11]),
    .Y(_012_)
  );
  NAND _138_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _139_ (
    .A(MONTO[12]),
    .B(_013_),
    .Y(_014_)
  );
  NOT _140_ (
    .A(_014_),
    .Y(_015_)
  );
  NOR _141_ (
    .A(MONTO[20]),
    .B(MONTO[21]),
    .Y(_016_)
  );
  NOR _142_ (
    .A(MONTO[22]),
    .B(MONTO[23]),
    .Y(_017_)
  );
  NAND _143_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _144_ (
    .A(MONTO[16]),
    .B(MONTO[17]),
    .Y(_019_)
  );
  NOR _145_ (
    .A(MONTO[18]),
    .B(MONTO[19]),
    .Y(_020_)
  );
  NAND _146_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _147_ (
    .A(_018_),
    .B(_021_),
    .Y(_022_)
  );
  NOT _148_ (
    .A(_022_),
    .Y(_023_)
  );
  NOR _149_ (
    .A(MONTO[13]),
    .B(MONTO[14]),
    .Y(_024_)
  );
  NAND _150_ (
    .A(_042_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _151_ (
    .A(MONTO[29]),
    .B(MONTO[30]),
    .Y(_026_)
  );
  NOR _152_ (
    .A(MONTO[24]),
    .B(MONTO[27]),
    .Y(_027_)
  );
  NAND _153_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _154_ (
    .A(_025_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _155_ (
    .A(MONTO[28]),
    .B(MONTO[31]),
    .Y(_030_)
  );
  NOR _156_ (
    .A(MONTO[25]),
    .B(MONTO[26]),
    .Y(_031_)
  );
  NAND _157_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _158_ (
    .A(_023_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _159_ (
    .A(_029_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _160_ (
    .A(_015_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _161_ (
    .A(_059_),
    .B(_035_),
    .Y(_036_)
  );
  NOT _162_ (
    .A(_036_),
    .Y(ENTREGAR_DINERO)
  );
  NAND _163_ (
    .A(_061_),
    .B(_036_),
    .Y(BALANCE_ACTUALIZADO)
  );
  NOR _164_ (
    .A(_058_),
    .B(_035_),
    .Y(FONDOS_INSUFICIENTES)
  );
  (* src = "controlador.v:26.1-38.4" *)
  DFF _165_ (
    .C(CLK),
    .D(_000_),
    .Q(estado[0])
  );
  (* src = "controlador.v:26.1-38.4" *)
  DFF _166_ (
    .C(CLK),
    .D(_001_),
    .Q(estado[1])
  );
  (* src = "controlador.v:26.1-38.4" *)
  DFF _167_ (
    .C(CLK),
    .D(_002_),
    .Q(estado[3])
  );
  (* src = "controlador.v:26.1-38.4" *)
  DFF _168_ (
    .C(CLK),
    .D(_003_),
    .Q(estado[4])
  );
  (* src = "controlador.v:26.1-38.4" *)
  DFF _169_ (
    .C(CLK),
    .D(_004_),
    .Q(estado[5])
  );
  (* src = "controlador.v:26.1-38.4" *)
  DFF _170_ (
    .C(CLK),
    .D(_005_),
    .Q(estado[6])
  );
  assign ADVERTENCIA = 1'h0;
  assign BALANCE = 32'd5000;
  assign BLOQUEO_CTRL = 1'h0;
  assign PIN_INCORRECTO = 1'h0;
  assign counter = 4'h0;
  assign estado[2] = estado[4];
  assign pin_ingresado = 16'hxxxx;
  assign proximo_estado[2] = proximo_estado[4];
endmodule
